# Generated by Django 4.2 on 2023-05-04 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiporol', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
                ('idrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('genero', models.CharField(max_length=45)),
                ('edad', models.IntegerField()),
                ('telefono', models.CharField(max_length=45)),
                ('cargo', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('usuarioid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.usuario')),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
    ]
